# fly.toml app configuration file generated for sample-charging on 2024-01-13T11:11:38-08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "sample-charging"
primary_region = "sea"
console_command = "/code/manage.py shell"

[build]

[env]
  PORT = "8000"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[processes]
  app = "gunicorn --bind :8000 --workers 2 --access-logfile - charging.wsgi"
  worker = "celery -A charging.celery worker --loglevel=info --concurrency=2"
  scheduler = "celery -A charging.celery beat --loglevel=info"

[deploy]
  release_command = "python manage.py migrate --noinput"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 2048

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 2048
  processes = ["worker"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512
  processes = ["scheduler"]

[[statics]]
  guest_path = "/code/staticfiles"
  url_prefix = "/static/"
