# Generated by Django 5.0.1 on 2024-01-22 05:19

from django.db import migrations
from django.contrib.postgres.operations import CreateExtension


class Migration(migrations.Migration):
    operations = [
        CreateExtension('postgis'),
    ]
