# Generated by Django 5.0.1 on 2024-01-22 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beacon', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='belongs_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='beacon.area'),
        ),
    ]
