# Generated by Django 5.0.1 on 2024-01-22 20:41

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beacon', '0005_canadianprovince_abbreviation_fr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canadianprovince',
            name='area',
            field=models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ca_state', to='beacon.area'),
        ),
        migrations.CreateModel(
            name='ForwardStatisticalArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('area', models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ca_fsa', to='beacon.area')),
            ],
        ),
    ]
