# Generated by Django 5.0.1 on 2024-01-22 22:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beacon', '0006_alter_canadianprovince_area_forwardstatisticalarea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forwardstatisticalarea',
            name='area',
            field=models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ca_zip', to='beacon.area'),
        ),
        migrations.AlterField(
            model_name='zipcodetabulationarea',
            name='area',
            field=models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='us_zip', to='beacon.area'),
        ),
    ]
