# Generated by Django 5.0.1 on 2024-01-23 04:03

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beacon', '0007_alter_forwardstatisticalarea_area_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326),
        ),
    ]
