# Generated by Django 5.0.1 on 2024-01-23 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beacon', '0008_area_geom'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='area',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='area',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
