# Generated by Django 5.0.1 on 2024-01-25 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beacon', '0009_alter_area_options_alter_area_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='search',
            name='exclude',
        ),
        migrations.AddField(
            model_name='search',
            name='daily_email',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='search',
            name='weekly_email',
            field=models.BooleanField(default=True),
        ),
    ]
