# Generated by Django 5.0.1 on 2024-01-26 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beacon', '0010_remove_search_exclude_search_daily_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
