# Generated by Django 5.0.1 on 2024-01-28 03:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_alter_historicalstation_ev_dc_fast_num_and_more'),
        ('beacon', '0011_search_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='last_notified_id',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='SearchResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idempotency_key', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('search', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beacon.search')),
                ('update', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.update')),
            ],
            options={
                'unique_together': {('search', 'update', 'idempotency_key')},
            },
        ),
    ]
