# Generated by Django 5.0.1 on 2024-01-29 04:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beacon', '0012_search_last_notified_id_searchresult'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='searchresult',
            options={'ordering': ['-created']},
        ),
        migrations.RenameField(
            model_name='search',
            old_name='last_notified_id',
            new_name='last_notified_timestamp',
        ),
        migrations.AlterField(
            model_name='searchresult',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='searchresult',
            name='search',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='beacon.search'),
        ),
    ]
