# Generated by Django 5.0.1 on 2024-01-29 04:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beacon', '0013_alter_searchresult_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='last_notified_timestamp',
            field=models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0, tzinfo=datetime.timezone.utc)),
        ),
    ]
