# Generated by Django 5.0.1 on 2024-01-30 00:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beacon', '0014_alter_search_last_notified_timestamp'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='searchresult',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='searchresult',
            old_name='created',
            new_name='created_at',
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('e', 'Email')], max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('message', models.JSONField()),
                ('search', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='beacon.search')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
