# Generated by Django 5.0.1 on 2024-01-13 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('access_code', models.CharField(blank=True, max_length=100, null=True)),
                ('access_days_time', models.CharField(blank=True, max_length=100, null=True)),
                ('access_detail_code', models.CharField(blank=True, max_length=100, null=True)),
                ('cards_accepted', models.CharField(blank=True, max_length=100, null=True)),
                ('date_last_confirmed', models.DateField(blank=True, null=True)),
                ('expected_date', models.DateField(blank=True, null=True)),
                ('fuel_type_code', models.CharField(blank=True, max_length=100, null=True)),
                ('groups_with_access_code', models.CharField(blank=True, max_length=100, null=True)),
                ('maximum_vehicle_class', models.CharField(blank=True, max_length=100, null=True)),
                ('open_date', models.DateField(blank=True, null=True)),
                ('owner_type_code', models.CharField(blank=True, max_length=100, null=True)),
                ('restricted_access', models.CharField(blank=True, max_length=100, null=True)),
                ('status_code', models.CharField(blank=True, max_length=100, null=True)),
                ('facility_type', models.CharField(blank=True, max_length=100, null=True)),
                ('station_name', models.CharField(blank=True, max_length=100, null=True)),
                ('station_phone', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('geocode_status', models.CharField(blank=True, max_length=100, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('intersection_directions', models.CharField(blank=True, max_length=100, null=True)),
                ('plus4', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('street_address', models.CharField(blank=True, max_length=100, null=True)),
                ('zip', models.CharField(blank=True, max_length=100, null=True)),
                ('ev_connector_types', models.JSONField(blank=True, null=True)),
                ('ev_dc_fast_num', models.IntegerField(blank=True, null=True)),
                ('ev_level1_evse_num', models.IntegerField(blank=True, null=True)),
                ('ev_level2_evse_num', models.IntegerField(blank=True, null=True)),
                ('ev_network', models.CharField(blank=True, max_length=100, null=True)),
                ('ev_network_web', models.URLField(blank=True, null=True)),
                ('ev_other_evse', models.CharField(blank=True, max_length=100, null=True)),
                ('ev_pricing', models.CharField(blank=True, max_length=100, null=True)),
                ('ev_renewable_source', models.CharField(blank=True, max_length=100, null=True)),
                ('ev_workplace_charging', models.BooleanField(blank=True, default=False, null=True)),
                ('nps_unit_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
