# Generated by Django 5.0.1 on 2024-01-13 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_historicalstation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalstation',
            name='access_code',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalstation',
            name='access_days_time',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalstation',
            name='access_detail_code',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalstation',
            name='cards_accepted',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalstation',
            name='city',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalstation',
            name='country',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalstation',
            name='ev_network',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalstation',
            name='ev_other_evse',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalstation',
            name='ev_pricing',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalstation',
            name='ev_renewable_source',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalstation',
            name='facility_type',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalstation',
            name='fuel_type_code',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalstation',
            name='geocode_status',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalstation',
            name='groups_with_access_code',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalstation',
            name='intersection_directions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalstation',
            name='maximum_vehicle_class',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalstation',
            name='nps_unit_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalstation',
            name='owner_type_code',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalstation',
            name='plus4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalstation',
            name='restricted_access',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalstation',
            name='state',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalstation',
            name='station_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalstation',
            name='station_phone',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalstation',
            name='status_code',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalstation',
            name='street_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalstation',
            name='zip',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='station',
            name='access_code',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='station',
            name='access_days_time',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='station',
            name='access_detail_code',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='station',
            name='cards_accepted',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='station',
            name='city',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='station',
            name='country',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='station',
            name='ev_network',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='station',
            name='ev_other_evse',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='station',
            name='ev_pricing',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='station',
            name='ev_renewable_source',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='station',
            name='facility_type',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='station',
            name='fuel_type_code',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='station',
            name='geocode_status',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='station',
            name='groups_with_access_code',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='station',
            name='intersection_directions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='station',
            name='maximum_vehicle_class',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='station',
            name='nps_unit_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='station',
            name='owner_type_code',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='station',
            name='plus4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='station',
            name='restricted_access',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='station',
            name='state',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='station',
            name='station_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='station',
            name='station_phone',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='station',
            name='status_code',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='station',
            name='street_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='station',
            name='zip',
            field=models.TextField(blank=True, null=True),
        ),
    ]
