# Generated by Django 5.0.1 on 2024-01-14 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_persona_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalstation',
            name='restricted_access',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='station',
            name='restricted_access',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
