# Generated by Django 5.0.1 on 2024-01-14 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_historicalstation_restricted_access_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='update',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddIndex(
            model_name='update',
            index=models.Index(fields=['station', 'created_at'], name='app_update_station_30c86d_idx'),
        ),
    ]
