# Generated by Django 5.0.1 on 2024-01-14 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_update_is_creation'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='linked',
            field=models.ManyToManyField(blank=True, related_name='linked_by', to='app.station'),
        ),
    ]
