# Generated by Django 5.0.1 on 2024-01-14 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_station_linked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='linked',
            field=models.ManyToManyField(blank=True, to='app.station'),
        ),
    ]
