# Generated by Django 5.0.1 on 2024-01-16 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_station_linked_historicalstation_linked_to_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalstation',
            name='ev_network_ids',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='station',
            name='ev_network_ids',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
