# Generated by Django 5.0.1 on 2024-01-16 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_historicalstation_ev_network_ids_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='update',
            name='persona',
        ),
        migrations.AlterField(
            model_name='historicalstation',
            name='linked_to',
            field=models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='app.station'),
        ),
        migrations.AlterField(
            model_name='station',
            name='linked_to',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked', to='app.station'),
        ),
        migrations.AlterField(
            model_name='update',
            name='station',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='app.station'),
        ),
    ]
