# Generated by Django 5.0.1 on 2024-01-18 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_remove_update_persona_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalstation',
            name='beacon_name',
            field=models.SlugField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='station',
            name='beacon_name',
            field=models.SlugField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
