# Generated by Django 5.0.1 on 2024-01-25 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_historicalstation_point_station_point'),
    ]

    operations = [
        migrations.AlterField(
            model_name='update',
            name='station',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='app.station'),
        ),
    ]
