# Generated by Django 5.0.1 on 2024-01-27 05:36

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_update_station'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalstation',
            name='ev_dc_fast_num',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalstation',
            name='ev_network',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='station',
            name='ev_dc_fast_num',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='station',
            name='ev_network',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='update',
            name='is_creation',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddIndex(
            model_name='station',
            index=django.contrib.postgres.indexes.GinIndex(fields=['ev_connector_types'], name='app_station_ev_conn_b91eea_gin'),
        ),
    ]
